#!/usr/bin/env bash
# launch.sh — Open iTerm2 with 4 agent panes and capture session IDs
#
# Usage: ./launch.sh
#
# Creates a new iTerm2 window split into 4 panes, starts Claude Code
# in each, and writes session UUIDs to pane-config.sh so that
# send-to-agent.sh can target the right pane.
#
# Layout:
#   ┌─────────────┬─────────────┐
#   │  Agent 1    │  Agent 2    │
#   │ (you/orch.) │             │
#   ├─────────────┼─────────────┤
#   │  Agent 3    │  Agent 4    │
#   │             │             │
#   └─────────────┴─────────────┘

set -e

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"

echo "Launching agent workspace in iTerm2..."

SESSION_IDS=$(osascript << APPLESCRIPT
tell application "iTerm2"
  activate

  -- Create a new window
  set newWindow to (create window with default profile)

  tell newWindow
    set agent1Session to current session of current tab

    -- Split right → Agent 2
    tell agent1Session
      set agent2Session to (split vertically with default profile)
    end tell

    -- Split Agent 1 down → Agent 3
    tell agent1Session
      set agent3Session to (split horizontally with default profile)
    end tell

    -- Split Agent 2 down → Agent 4
    tell agent2Session
      set agent4Session to (split horizontally with default profile)
    end tell

    -- Label and start Claude in each pane
    tell agent1Session
      write text "printf '\\033]0;Agent 1 — Orchestrator\\007' && cd '$SCRIPT_DIR' && claude"
    end tell
    tell agent2Session
      write text "printf '\\033]0;Agent 2\\007' && cd '$SCRIPT_DIR' && claude"
    end tell
    tell agent3Session
      write text "printf '\\033]0;Agent 3\\007' && cd '$SCRIPT_DIR' && claude"
    end tell
    tell agent4Session
      write text "printf '\\033]0;Agent 4\\007' && cd '$SCRIPT_DIR' && claude"
    end tell

    -- Return session IDs
    set id1 to unique id of agent1Session
    set id2 to unique id of agent2Session
    set id3 to unique id of agent3Session
    set id4 to unique id of agent4Session

    return id1 & "," & id2 & "," & id3 & "," & id4
  end tell
end tell
APPLESCRIPT
)

# Parse the four UUIDs
IFS=',' read -r ID1 ID2 ID3 ID4 <<< "$SESSION_IDS"

# Write pane-config.sh
cat > "$SCRIPT_DIR/pane-config.sh" << EOF
# iTerm2 pane session IDs — generated by launch.sh on $(date)
# Re-run ./launch.sh to regenerate after restarting iTerm2
AGENT_1_SESSION="$ID1"
AGENT_2_SESSION="$ID2"
AGENT_3_SESSION="$ID3"
AGENT_4_SESSION="$ID4"
EOF

echo ""
echo "✓ iTerm2 workspace launched"
echo "✓ pane-config.sh written"
echo ""
echo "  Agent 1 (you): $ID1"
echo "  Agent 2:       $ID2"
echo "  Agent 3:       $ID3"
echo "  Agent 4:       $ID4"
echo ""
echo "Claude is starting in each pane."
echo "You are Agent 1 — the orchestrator. Start by giving it a Jira ticket URL."
echo ""
echo "To send a message to another agent:"
echo "  ./send-to-agent.sh 2 \"Your message here\""
